# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/109-AA3pG0xb-1XTHtuKQGC8O4lI25XCi
"""

from datetime import datetime

class Booking:
    def __init__(self, booking_id, guest, room, check_in_date, check_out_date):
        self.__booking_id = booking_id
        self.__guest = guest
        self.__room = room
        self.__check_in_date = datetime.strptime(check_in_date, "%Y-%m-%d")
        self.__check_out_date = datetime.strptime(check_out_date, "%Y-%m-%d")
        self.__total_price = self.calculate_total_price()

    def calculate_total_price(self):
        nights = (self.__check_out_date - self.__check_in_date).days
        return nights * self.__room._Room__price_per_night

    def confirm_booking(self):
        self.__room.update_availability(False)
        return f"Booking {self.__booking_id} confirmed for {self.__guest._Guest__name}."

    def __str__(self):
        return f"Booking ID: {self.__booking_id}, Guest: {self.__guest._Guest__name}, Room: {self.__room._Room__room_number}, Total: ${self.__total_price}"