# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/109-AA3pG0xb-1XTHtuKQGC8O4lI25XCi
"""

class Payment:
    def __init__(self, payment_id, booking, amount, payment_method):
        self.__payment_id = payment_id
        self.__booking = booking
        self.__amount = amount
        self.__payment_method = payment_method
        self.__status = "Pending"

    def process_payment(self):
        self.__status = "Completed"
        return f"Payment {self.__payment_id} of ${self.__amount} via {self.__payment_method} completed."