# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/109-AA3pG0xb-1XTHtuKQGC8O4lI25XCi
"""

class Room:
    def __init__(self, room_number, room_type, amenities, price_per_night, availability_status=True):
        self.__room_number = room_number
        self.__room_type = room_type
        self.__amenities = amenities
        self.__price_per_night = price_per_night
        self.__availability_status = availability_status

    def update_availability(self, status):
        self.__availability_status = status

    def get_details(self):
        return f"Room {self.__room_number}: {self.__room_type}, Amenities: {', '.join(self.__amenities)}, Price: ${self.__price_per_night}, Available: {self.__availability_status}"

    def __str__(self):
        return self.get_details()