# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lrs2l1JznioLdxl01rvmydRasvo5oKTw
"""

class TestBooking(unittest.TestCase):
    def test_booking_creation(self):
        guest = Guest("John Doe", "john@example.com", "1234567890")
        room = Room(101, "Single", ["Wi-Fi", "TV"], 100)
        booking = Booking(1, guest, room, "2025-03-25", "2025-03-27")
        self.assertEqual(booking.calculate_total_price(), 200)

    def test_booking_confirmation(self):
        guest = Guest("Alice", "alice@example.com", "9876543210")
        room = Room(102, "Double", ["Wi-Fi", "Mini-Bar"], 150)
        booking = Booking(2, guest, room, "2025-03-25", "2025-03-28")
        self.assertIn("confirmed", booking.confirm_booking())